abbr catp "cat package.json"
abbr cats "cat package.json | jq '.scripts'"
abbr catd "cat package.json | jq '.dependencies'"
abbr catdd "cat package.json | jq '.devDependencies'"
abbr catbd "cat bsconfig.json | jq '.bs-dependencies'"
abbr catbdd "cat bsconfig.json | jq '.bs-dev-dependencies'"
abbr catgql "cat bsconfig.json | jq '.graphql'"
abbr catppx "cat bsconfig.json | jq '.ppx-flags'"
